### ISSUE TITLE
Ubuntu: Check if libdevmapper1.02.1 should be installed

### ISSUE THREAD

**Issue by ebocchi** [sciencebox/mboxed#5]
Unclear whether it should be explicitly installed as dependency for docker/containerd or it will be automatically fetched by system repos

**Comment by jimil749** [comment]
I am not sure because testing the installation script on my local machine as well as on the fresh VM (without docker or any dependency installed) worked just fine.

**Comment by ebocchi** [comment]
Ok, let's assume it is not a problem for now. I guess it is provided by some repo configure system-wide.
